### ISSUE TITLE
Guard has 11 turns after player died once

### ISSUE THREAD

**Issue by emiljaregran** [tsoding/eepers#17]
After dying in the first guard fight, the guard seems to start with 11 turns instead of the normal 10 turns.
![Screenshot from 2024-03-25 05-08-05](https://github.com/tsoding/eepers/assets/45233952/d16ef40d-6d6b-46fc-a692-3ced94683bc9)

**Comment by rexim** [comment]
Yeah, it's a known issue. I actually knew about it before the v1.0 release, but didn't fix it because I didn't have time. Thank you for reporting it!
