### ISSUE TITLE
Increment in Ada was added in Ada 2022

### ISSUE THREAD

**Issue by Lucretia** [tsoding/eepers#26]
You can do:

```ada
Long_Identifier := @ + 1;
```

[Overview](http://www.ada-auth.org/standards/22over/html/Ov22-7-7.html#I1315)

**Comment by LainLayer** [comment]
As this is an Ada 2022 feature, it is not applicable. this project was moved to support Ada 2012 as many people are on systems that do not have gnatmake with 2022 support yet.

Also this is not an issue with eepers

**Comment by Lucretia** [comment]
> As this is an Ada 2022 feature, it is not applicable. this project was moved to support Ada 2012 as many people are on systems that do not have gnatmake with 2022 support yet.

Majority of oses has gcc 12+ now, so.

> Also this is not an issue with eepers

Nowhere else to put it and I'm not going to create a PR.
