### ISSUE TITLE
Players with bigger screens get an advantage

### ISSUE THREAD

**Issue by astef** [tsoding/eepers#3]
The amount of map you're able to see is determined by screen resolution.

On a small screen you only see a small portion of map, which makes playing the game objectively harder (when fighting shreks, they often get out of your control)

On a large enough screen, or multiple screens (when manually resize the game window), you can see the entire map even.

**Comment by rexim** [comment]
Eeeh... I dunno... I don't think it's that big of an advantage, honestly.
