### ISSUE TITLE
MacOS M chip support

### ISSUE THREAD

**Issue by sharpvik** [tsoding/eepers#32]
Would it be possible to cross-compile the game to support newer Mac models that use M chips?

**Comment by Kensan** [comment]
You can use the macOS build script in combination with the aarch64 toolchain, see https://github.com/tsoding/eepers/pull/13#issuecomment-2016862353 for instructions regarding where to get the toolchain.

**Comment by sharpvik** [comment]
@Kensan [This is the comment that worked for me really well.](https://github.com/tsoding/eepers/pull/13#issuecomment-2016933611) I managed to compile the whole thing and it works without a single issue. 

The room with 4 monsters is really hard. IDK how to get through.

The issue should be closed though. Thanks for the assistance!
