### ISSUE TITLE
Quick second key press is ignored

### ISSUE THREAD

**Issue by astef** [tsoding/eepers#4]
When quickly pressing two buttons one after another, only the first one is affecting the game. Giving bigger delay between them helps, but that delay is pretty annoyingly big. After playing for 15 minutes, it's the mostly annoying thing which discourages me from trying more.

**Comment by astef** [comment]
Issue reproduces with different keys only. Pressing one key quickly performs much better.

**Comment by rexim** [comment]
You actually gave me a good idea on how to improve the controls. Thank you! I'll see what I can do...

**Comment by rexim** [comment]
Tried to fix it in v1.1 https://github.com/tsoding/eepers/releases/tag/v1.1 Please let me know if it feels better for you

**Comment by astef** [comment]
Fixed, thank you!
