### ISSUE TITLE
Last room can be easily skipped

### ISSUE THREAD

**Issue by 0dminnimda** [tsoding/eepers#7]
The blue eeper can block other eepera from attacking in the direction of the blocker

Here's an example of how to execute this:
https://youtu.be/lPbT_ytxkFw (Specifically at 1:40)

It doesn't seem intended, so either a bug, or an easter egg of sort, since it's a general mechanic that one eeper blocks another's path.
The fix would probably be updating blue eeper ai to not walk to places where it would block path to the mother

**Comment by rexim** [comment]
Hi! I got another report that independently discovered this too! :D I'm actually not sure what to do about this one. Mother by itself is pretty difficult. So maybe we could make it optional like that? I'll think about it. Thank you for the report anyway!

**Comment by rexim** [comment]
Ok, after days of watching people play the game I officially declare this a feature!
