### ISSUE TITLE
Attempt to insert key already in map when killing first Gnome

### ISSUE THREAD

**Issue by AlexViaColl** [tsoding/eepers#8]
I got the following error when killing the first Gnome:
`raised CONSTRAINT_ERROR : Eepers.Hashed_Map_Items.Insert: attempt to insert key already in map`

Unfortunately I wasn't able to reproduce it again due to the RNG. Maybe the gnome was at the bomb spawn point at the time of death and that caused a double insert to the hashmap with the same key, but I'm not 100%

Otherwise, the game is great and I totally understand if you don't have time to fix this.

**Comment by rexim** [comment]
Oh, I didn't think about this situation... Thank you for reporting it!

**Comment by rexim** [comment]
Tried to fix it in v1.1 https://github.com/tsoding/eepers/releases/tag/v1.1
