### ISSUE TITLE
The boss kills you on the same turn he dies from the bomb

### ISSUE THREAD

**Issue by ProgKea** [tsoding/eepers#9]
I was speedrunning the game and died at the same time the boss did. So if the boss is one hit and he charges at you while the bomb explodes both of you die.

**Comment by rexim** [comment]
Does it look weird visually?

**Comment by ProgKea** [comment]
It does look weird

https://github.com/tsoding/eepers/assets/97286671/c1ad7dec-493c-46c6-98b3-d89c56c6b15a

Bug happens at 00:32

**Comment by rexim** [comment]
Oooh! Thank you so much for the video! I'll see what I can do!
